name: Comment to the merged pull request
on:
  push:
    branches:
      - main

jobs:
  comment:
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Pass the relative path to use the action
      - uses: ./
        id: merged-pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Comment to the merged pull request"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const pr_number = "${{ steps.merged-pr-info.outputs.pull-request-number }}";
            const body = `@${{ steps.merged-pr-info.outputs.pull-request-creator }}
            How are you?
            \`The back quotes have to be escaped.\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: body
            });
            console.log(`Commented to the pull request ${pr_number}`);
